# Generated by Django 4.1.7 on 2023-05-18 09:13

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(default='', null=True, upload_to=orders.models.Product.thumbnail_directory_path, verbose_name='Hình ảnh'),
        ),
    ]
