# Generated by Django 4.1.7 on 2023-06-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('store_manager', 'Store Manager'), ('customer', 'Customer'), ('employee', 'Employee')], default='customer', max_length=20),
        ),
    ]
