# Generated by Django 4.1.7 on 2023-06-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftCode',
        ),
    ]
