# Generated by Django 4.1.7 on 2023-06-28 03:19

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_giftcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('thumbnail', models.FileField(default='', null=True, upload_to=orders.models.Store.thumbnail_directory_path, verbose_name='Hình ảnh')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Category'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Product category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store_operate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.store'),
        ),
        migrations.AddField(
            model_name='discountpackage',
            name='store_operate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.store'),
        ),
        migrations.AddField(
            model_name='orderplace',
            name='store_operate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store_operate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.store'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='store_operate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.store'),
        ),
    ]
