# Generated by Django 4.1.7 on 2023-05-19 09:32

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productcategory_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('thumbnail', models.FileField(default='', null=True, upload_to=orders.models.DiscountPackage.thumbnail_directory_path, verbose_name='Hình ảnh')),
            ],
        ),
    ]
