# Generated by Django 4.1.7 on 2023-05-23 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.table'),
        ),
    ]
