# Generated by Django 4.1.7 on 2023-05-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderplace_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplace',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
    ]
