# Generated by Django 4.1.7 on 2023-05-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderplace_is_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.discountpackage'),
        ),
    ]
