# Generated by Django 4.1.7 on 2023-05-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderplace_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.discountpackage'),
        ),
    ]
