# Generated by Django 4.1.7 on 2023-05-23 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderplace_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('order_place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderplace')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
        ),
    ]
