# Generated by Django 4.1.7 on 2023-06-19 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplace',
            old_name='time',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='orderplaceproduct',
            old_name='order_place_id',
            new_name='order_place',
        ),
        migrations.RemoveField(
            model_name='orderplace',
            name='is_pay',
        ),
        migrations.AddField(
            model_name='orderplace',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.customuser'),
        ),
        migrations.AddField(
            model_name='orderplace',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='orderplace',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderplaceproduct',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplaceproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
