# Generated by Django 4.1.7 on 2023-06-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_time_orderplace_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaceproduct',
            name='price',
        ),
    ]
