# Generated by Django 4.1.7 on 2023-07-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0004_alter_product_price_alter_product_store_operate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Table name')),
                ('number_of_chair', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderplace',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplace',
            name='order_type',
            field=models.CharField(choices=[('onsite', 'On-site Service'), ('delivery', 'Delivery')], default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplace',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('serving', 'Serving'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaceproduct',
            name='order_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order_api.orderplace'),
        ),
    ]
