# Generated by Django 4.1.7 on 2023-07-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0005_ordertype_orderplace_is_paid_orderplace_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
