# Generated by Django 4.1.7 on 2023-07-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0006_alter_orderplace_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountpackage',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discountpackage',
            name='gift_code',
            field=models.TextField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discountpackage',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
