# Generated by Django 4.1.7 on 2023-07-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0007_discountpackage_available_discountpackage_gift_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountpackage',
            name='gift_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True, unique=True),
        ),
    ]
