# Generated by Django 4.1.7 on 2023-07-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0010_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
