# Generated by Django 4.1.7 on 2023-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0011_alter_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='order_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
