# Generated by Django 4.1.7 on 2023-07-13 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0012_alter_orderplace_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplace',
            name='order_date',
        ),
        migrations.AddField(
            model_name='orderplace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
