# Generated by Django 4.1.7 on 2023-07-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0013_remove_orderplace_order_date_orderplace_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
